name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: start running unit tests
        run: Start running unit tests
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - uses: php-actions/phpunit@v1