name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            coverage: "none"
            extensions: "json"
            ini-values: "memory_limit=-1"
            php-version: 7.4
      -   name: Determine composer cache directory
          id: composer-cache
          run: echo "::set-output name=directory::$(composer config cache-dir)"

      -   name: Cache composer dependencies
          uses: actions/cache@v1
          with:
            path: ${{ steps.composer-cache.outputs.directory }}
            key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: ${{ matrix.php }}-composer-
      -   name: Install dependencies
          run: |
            composer install --no-progress --no-suggest --ansi
      -   name: Run tests
          run: ./vendor/phpunit/phpunit